# Generated by Django 3.2.4 on 2021-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=25)),
                ('role', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
