version: "3"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "vasan212001"
      POSTGRES_DB: users_crud_task2
